format = """
[â–ˆ](cyan)\
$os\
$username\
[ğŸ¬¶ğœµŸğœ´»ğœ´ƒ](bg:red fg:cyan)\
$directory\
[â—¤](fg:red bg:orange)\
$git_branch\
$git_status\
[â—¤](fg:orange bg:yellow)\
$c\
$cpp\
$elixir\
$elm\
$golang\
$haskell\
$python\
$java\
$kotlin\
$gradle\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[â—¤](fg:yellow bg:pink)\
$docker_context\
[â—¤](fg:pink bg:blue)\
$time\
[î‚´ ](fg:blue)\
"""

palette = 'everforest'
# Disable the blank line at the start of the prompt
# add_newline = false
"$schema" = 'https://starship.rs/config-schema.json'
# You can also replace your username with a neat symbol like ï„   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:cyan"
style_root = "bg:cyan"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:cyan"
disabled = true # Disabled by default

[directory]
style = "bg:red"
read_only = " ó°Œ¾"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ó°š "
"Pictures" = "ï€¾ "
"Developer" = "ó°²‹ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ó°ˆ™ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ó°ˆ™ " = " ó°ˆ™ï„ª "
[c]
symbol = "î˜ "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = "î˜ "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[cmake]
symbol = "î” "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:green"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = "î‰µ "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = "ï˜"
style = "bg:orange"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:orange"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "î· "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "î‰– "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[kotlin]
symbol = "î˜´ "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = "î˜  "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[meson]
symbol = "ó°”· "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "ó°†¥ "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[perl]
symbol = "î™¾ "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[php]
symbol = "î˜ˆ "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "î˜†"
style = "bg:yellow"
format = '[ $symbol( $version)(\(#$virtualenv\)) ]($style)'

[rust]
symbol = "î¨"
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[ruby]
symbol = "î‘ "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = "îœ· "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[zig]
symbol = "îš© "
style = "bg:yellow"
format = '[ $symbol ($version) ]($style)'

[package]
symbol = "ó°— "

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:blue"
format = '[ â™¥ $time ]($style)'

[character]
disabled = false
success_symbol = '[â¯](bold fg:green)'
error_symbol = '[â¯](bold fg:red)'
vimcmd_symbol = '[â®](bold fg:green)'
vimcmd_replace_one_symbol = '[â®](bold fg:pink)'
vimcmd_replace_symbol = '[â®](bold fg:pink)'
vimcmd_visual_symbol = '[â®](bold fg:yellow)'

[palettes.everforest]
#: black
black = "#343f44"
light-black = "#868d80"
red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"
orange = "#e69875"
blue = "#7fbbb3"
pink = "#d699b6"
cyan = "#83c092"
white = "#859289"
ligh-white = "#9da9a0"
